/**
 * app/api/export/route.ts — Analysis Export
 * ─────────────────────────────────────────────────────────────────────────────
 * POST /api/export
 *
 * Accepts a structured analysis JSON payload and returns a formatted
 * Markdown document ready for download, copy into Notion/Linear, or
 * printing to PDF via the browser's native print dialog.
 *
 * Supported payload shapes:
 *   - Upwind / Downwind  (executive schema with headline, signal, actions)
 *   - Trim               (phased timeline)
 *   - Catamaran          (dual-track)
 *   - Raw markdown       (from Sail / Operator / Personalised streams)
 *
 * Returns: text/markdown with a Content-Disposition attachment header.
 */

import { NextRequest, NextResponse } from 'next/server'
import { auth }                      from '@/auth'

// ── Types (mirrors AetherisPayload shapes) ────────────────────────────────────

interface ActionItem {
  action:    string
  owner?:    string
  timeline?: string
  kpi?:      string
}

interface ExecutivePayload {
  headline?:     string
  signal?:       string
  insight?:      string
  actions?:      ActionItem[]
  target30?:     string
  greatestRisk?: string
  sources?:      string[]
  mode?:         string
  query?:        string
}

interface TrimPhase {
  phase:     string | number
  title:     string
  objective: string
  actions?:  string[]
  kpi?:      string
  timeline?: string
}

interface TrimPayload {
  trimTitle?:  string
  summary?:    string
  phases?:     TrimPhase[]
  query?:      string
}

interface CatamaranTrack {
  actions?: string[]
  target?:  string
}

interface CatamaranPayload {
  catamaranTitle?:     string
  marketGrowth?:       CatamaranTrack
  customerExperience?: CatamaranTrack
  unifiedStrategy?:    string
  thirtyDayTarget?:    string
  greatestRisk?:       string
  query?:              string
}

interface RawMarkdownPayload {
  markdown: string
  title?:   string
  query?:   string
}

type ExportPayload = (ExecutivePayload | TrimPayload | CatamaranPayload | RawMarkdownPayload) & {
  _type?: 'executive' | 'trim' | 'catamaran' | 'markdown'
}

// ── Markdown formatters ───────────────────────────────────────────────────────

function formatExecutive(p: ExecutivePayload, query?: string): string {
  const now   = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
  const lines = [
    `# ${p.headline ?? 'Strategic Analysis'}`,
    `*Sail AI — ${now}*`,
    '',
  ]

  if (query) {
    lines.push(`> **Query:** ${query}`, '')
  }

  if (p.signal) {
    lines.push('## Executive Signal', p.signal, '')
  }

  if (p.insight) {
    lines.push('## Insight', p.insight, '')
  }

  if (p.actions?.length) {
    lines.push('## Recommended Actions', '')
    p.actions.forEach((a, i) => {
      lines.push(`### ${i + 1}. ${a.action}`)
      if (a.timeline) lines.push(`- **Timeline:** ${a.timeline}`)
      if (a.kpi)      lines.push(`- **KPI:** ${a.kpi}`)
      if (a.owner)    lines.push(`- **Owner:** ${a.owner}`)
      lines.push('')
    })
  }

  if (p.target30) {
    lines.push('## 30-Day Target', p.target30, '')
  }

  if (p.greatestRisk) {
    lines.push('## Greatest Risk', `⚠️ ${p.greatestRisk}`, '')
  }

  if (p.sources?.length) {
    lines.push('## Sources', ...p.sources.map(s => `- ${s}`), '')
  }

  lines.push('---', '*Generated by Sail AI — sovereign intelligence for independent operators.*')
  return lines.join('\n')
}

function formatTrim(p: TrimPayload, query?: string): string {
  const now   = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
  const lines = [
    `# ${p.trimTitle ?? 'Strategic Roadmap'}`,
    `*Sail AI TRIM Mode — ${now}*`,
    '',
  ]

  if (query) lines.push(`> **Query:** ${query}`, '')
  if (p.summary) lines.push('## Summary', p.summary, '')

  if (p.phases?.length) {
    lines.push('## Execution Phases', '')
    p.phases.forEach(ph => {
      lines.push(`### Phase ${ph.phase}: ${ph.title}`)
      lines.push(`**Objective:** ${ph.objective}`)
      if (ph.timeline) lines.push(`**Timeline:** ${ph.timeline}`)
      if (ph.kpi)      lines.push(`**KPI:** ${ph.kpi}`)
      if (ph.actions?.length) {
        lines.push('', '**Actions:**')
        ph.actions.forEach(a => lines.push(`- ${a}`))
      }
      lines.push('')
    })
  }

  lines.push('---', '*Generated by Sail AI — TRIM Mode.*')
  return lines.join('\n')
}

function formatCatamaran(p: CatamaranPayload, query?: string): string {
  const now   = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
  const lines = [
    `# ${p.catamaranTitle ?? 'Dual-Track Strategy'}`,
    `*Sail AI Catamaran Mode — ${now}*`,
    '',
  ]

  if (query) lines.push(`> **Query:** ${query}`, '')

  if (p.marketGrowth) {
    lines.push('## Track A: Market Growth', '')
    p.marketGrowth.actions?.forEach(a => lines.push(`- ${a}`))
    if (p.marketGrowth.target) lines.push(`**Target:** ${p.marketGrowth.target}`)
    lines.push('')
  }

  if (p.customerExperience) {
    lines.push('## Track B: Customer Experience', '')
    p.customerExperience.actions?.forEach(a => lines.push(`- ${a}`))
    if (p.customerExperience.target) lines.push(`**Target:** ${p.customerExperience.target}`)
    lines.push('')
  }

  if (p.unifiedStrategy)  lines.push('## Unified Strategy',  p.unifiedStrategy,  '')
  if (p.thirtyDayTarget)  lines.push('## 30-Day Target',     p.thirtyDayTarget,  '')
  if (p.greatestRisk)     lines.push('## Greatest Risk',     `⚠️ ${p.greatestRisk}`, '')

  lines.push('---', '*Generated by Sail AI — Catamaran Mode.*')
  return lines.join('\n')
}

// ── Route handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const session = await auth()
  if (!session?.user?.email) {
    return NextResponse.json({ error: 'Authentication required.' }, { status: 401 })
  }

  let body: ExportPayload
  try {
    body = await req.json() as ExportPayload
  } catch {
    return NextResponse.json({ error: 'Invalid JSON.' }, { status: 400 })
  }

  const query = (body as Record<string, unknown>).query as string | undefined
  let markdown: string

  // Detect payload type and format accordingly
  if ('markdown' in body && typeof (body as RawMarkdownPayload).markdown === 'string') {
    const p = body as RawMarkdownPayload
    const now = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    markdown = [
      `# ${p.title ?? 'Sail AI Analysis'}`,
      `*Sail AI — ${now}*`,
      '',
      query ? `> **Query:** ${query}\n` : '',
      p.markdown,
      '',
      '---',
      '*Generated by Sail AI — sovereign intelligence for independent operators.*',
    ].join('\n')
  } else if ('phases' in body) {
    markdown = formatTrim(body as TrimPayload, query)
  } else if ('marketGrowth' in body || 'customerExperience' in body) {
    markdown = formatCatamaran(body as CatamaranPayload, query)
  } else {
    markdown = formatExecutive(body as ExecutivePayload, query)
  }

  // Slug the headline/title for the filename
  const rawTitle = (
    (body as ExecutivePayload).headline   ??
    (body as TrimPayload).trimTitle       ??
    (body as CatamaranPayload).catamaranTitle ??
    (body as RawMarkdownPayload).title    ??
    'sail-analysis'
  )
  const slug = rawTitle
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)
  const filename = `${slug}-${new Date().toISOString().slice(0, 10)}.md`

  return new NextResponse(markdown, {
    headers: {
      'Content-Type':        'text/markdown; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control':       'no-store',
    },
  })
}
