import type { Metadata } from 'next'
import { LegalPage, LegalSection } from '@/components/LegalPage'
import {
  SUPPORT_EMAIL,
  LEGAL_ENTITY,
  JURISDICTION,
  REFUND_DAYS,
  MERCHANT_OF_RECORD,
} from '@/lib/legal'

export const metadata: Metadata = {
  title: 'Terms of Service · Sail AI',
  description: 'The terms governing your use of Sail AI.',
}

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      subtitle={`These terms form the agreement between you and ${LEGAL_ENTITY} when you use this service. Please read them before subscribing.`}
    >
      <LegalSection title="1. Who you are contracting with">
        <p>
          {LEGAL_ENTITY} is operated by an individual sole trader based in {JURISDICTION}.
          There is no incorporated company behind the service. You can reach the operator at{' '}
          <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
        </p>
        <p>
          Payments are processed by {MERCHANT_OF_RECORD}, which acts as the merchant
          of record. This means {MERCHANT_OF_RECORD} is the legal seller for the
          transaction, issues your invoice, and collects and remits any applicable
          VAT or sales tax in your jurisdiction. Your bank or card statement will
          show {MERCHANT_OF_RECORD} rather than {LEGAL_ENTITY}.
        </p>
      </LegalSection>

      <LegalSection title="2. What the service does">
        <p>
          Sail AI is a business intelligence assistant. It accepts questions in
          natural language, optionally analyses data files you upload, applies
          strategic frameworks, and produces written analysis and charts you can
          export.
        </p>
        <p>
          The service is provided on a subscription basis with a free tier subject
          to a daily usage limit, and a paid tier with a higher limit and
          additional features.
        </p>
      </LegalSection>

      <LegalSection title="3. Accounts">
        <p>
          You need an account to use the service. You are responsible for keeping
          your sign-in credentials secure and for activity that occurs under your
          account. Tell us promptly if you believe your account has been accessed
          without your permission.
        </p>
        <p>
          You must be at least 18 years old, or the age of majority in your
          jurisdiction, to enter into this agreement.
        </p>
      </LegalSection>

      <LegalSection title="4. Acceptable use">
        <p>You agree not to:</p>
        <ul>
          <li>Use the service to break the law or infringe anyone&apos;s rights.</li>
          <li>
            Upload data you have no right to process, including personal data you
            are not authorised to share.
          </li>
          <li>
            Attempt to circumvent usage limits, rate limits, or access controls,
            including by creating multiple accounts to obtain additional free
            allowance.
          </li>
          <li>
            Probe, scan, overload or reverse engineer the service or its underlying
            infrastructure.
          </li>
          <li>Resell or redistribute access to the service without written permission.</li>
        </ul>
        <p>
          We may suspend or terminate accounts that breach these rules. Where the
          breach is not deliberate we will normally contact you first.
        </p>
      </LegalSection>

      <LegalSection title="5. Your content and your data">
        <p>
          You keep ownership of everything you upload and of the outputs generated
          for you. We claim no licence over your business data beyond what is
          needed to operate the service for you: storing it, transmitting it to the
          AI providers listed in our{' '}
          <a href="/privacy">Privacy Policy</a>, and returning results to you.
        </p>
        <p>
          We do not use your uploaded data or conversations to train AI models.
        </p>
      </LegalSection>

      <LegalSection title="6. AI output — important limitations">
        <p>
          Output is generated by large language models. It can be incomplete,
          out of date, or confidently wrong. It is <strong>not</strong> financial,
          legal, tax, investment or professional advice.
        </p>
        <p>
          You are responsible for verifying anything you rely on. Do not make
          consequential business, financial or legal decisions on the basis of
          output from this service without independent professional review.
        </p>
        <p>
          Where the service cites external sources, those sources belong to third
          parties and we do not warrant their accuracy or availability.
        </p>
      </LegalSection>

      <LegalSection title="7. Subscriptions, billing and cancellation">
        <p>
          Paid plans renew automatically at the interval shown at checkout until
          cancelled. The price at the time you subscribe applies for that billing
          period.
        </p>
        <p>
          You can cancel at any time from your account settings or by emailing{' '}
          <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. Cancellation
          stops future renewals; you keep access until the end of the period you
          have already paid for.
        </p>
        <p>
          Refunds are governed by our <a href="/refund">Refund Policy</a>, which
          gives you {REFUND_DAYS} days to change your mind.
        </p>
        <p>
          If we change prices, we will give you notice before the change takes
          effect for your subscription, and you may cancel instead of accepting the
          new price.
        </p>
      </LegalSection>

      <LegalSection title="8. Availability">
        <p>
          We aim to keep the service available but do not guarantee uninterrupted
          operation. The service depends on third-party infrastructure and AI
          providers, and those can fail or change their terms. We may carry out
          maintenance, and we may modify or discontinue features.
        </p>
        <p>
          If we discontinue the service entirely, we will give reasonable notice
          and refund the unused portion of any prepaid period.
        </p>
      </LegalSection>

      <LegalSection title="9. Liability">
        <p>
          To the extent permitted by law, our total liability arising from the
          service is limited to the amount you paid in the twelve months before the
          event giving rise to the claim.
        </p>
        <p>
          We are not liable for lost profits, lost revenue, lost data, or indirect
          or consequential losses, including decisions taken on the basis of AI
          output.
        </p>
        <p>
          Nothing in these terms excludes liability that cannot be excluded by law,
          including your statutory rights as a consumer.
        </p>
      </LegalSection>

      <LegalSection title="10. Changes to these terms">
        <p>
          We may update these terms. If a change materially reduces your rights we
          will notify you by email or in the application before it takes effect.
          Continuing to use the service after that point means you accept the
          revised terms.
        </p>
      </LegalSection>

      <LegalSection title="11. Governing law">
        <p>
          These terms are governed by the laws of {JURISDICTION}. If you are a
          consumer resident elsewhere, this does not deprive you of the protection
          of mandatory consumer law in your country of residence.
        </p>
      </LegalSection>

      <LegalSection title="12. Contact">
        <p>
          Questions about these terms:{' '}
          <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. See our{' '}
          <a href="/contact">Contact page</a> for response times.
        </p>
      </LegalSection>
    </LegalPage>
  )
}
